In [ ]:
!pip uninstall -y torch torchvision torchaudio transformers accelerate fastai timm

Found existing installation: torch 2.3.1
Uninstalling torch-2.3.1:
  Successfully uninstalled torch-2.3.1
Found existing installation: torchvision 0.18.1
Uninstalling torchvision-0.18.1:
  Successfully uninstalled torchvision-0.18.1
WARNING: Skipping torchaudio as it is not installed.
Found existing installation: transformers 4.41.2
Uninstalling transformers-4.41.2:
  Successfully uninstalled transformers-4.41.2
Found existing installation: accelerate 0.29.3
Uninstalling accelerate-0.29.3:
  Successfully uninstalled accelerate-0.29.3
WARNING: Skipping fastai as it is not installed.
WARNING: Skipping timm as it is not installed.

In [ ]:
!pip install \
torch==2.3.1 \
torchvision==0.18.1 \
transformers==4.40.2 \
accelerate==0.29.3 \
scikit-learn pandas

Collecting torch==2.3.1
  Using cached torch-2.3.1-cp312-cp312-manylinux1_x86_64.whl.metadata (26 kB)
Collecting torchvision==0.18.1
  Using cached torchvision-0.18.1-cp312-cp312-manylinux1_x86_64.whl.metadata (6.6 kB)
Collecting transformers==4.40.2
  Downloading transformers-4.40.2-py3-none-any.whl.metadata (137 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 138.0/138.0 kB 12.3 MB/s eta 0:00:00
Collecting accelerate==0.29.3
  Using cached accelerate-0.29.3-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch==2.3.1) (3.20.3)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.12/dist-packages (from torch==2.3.1) (4.15.0)
Requirement already satisfied: sympy in /usr/local/lib/python3.12/dist-packages (from torch==2.3.1) (1.14.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch==2.3.1) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch==2.3.1) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from torch==2.3.1) (2025.3.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /usr/local/lib/python3.12/dist-packages (from torch==2.3.1) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /usr/local/lib/python3.12/dist-packages (from torch==2.3.1) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /usr/local/lib/python3.12/dist-packages (from torch==2.3.1) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==8.9.2.26 in /usr/local/lib/python3.12/dist-packages (from torch==2.3.1) (8.9.2.26)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /usr/local/lib/python3.12/dist-packages (from torch==2.3.1) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /usr/local/lib/python3.12/dist-packages (from torch==2.3.1) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /usr/local/lib/python3.12/dist-packages (from torch==2.3.1) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /usr/local/lib/python3.12/dist-packages (from torch==2.3.1) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /usr/local/lib/python3.12/dist-packages (from torch==2.3.1) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.20.5 in /usr/local/lib/python3.12/dist-packages (from torch==2.3.1) (2.20.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /usr/local/lib/python3.12/dist-packages (from torch==2.3.1) (12.1.105)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from torchvision==0.18.1) (2.0.2)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from torchvision==0.18.1) (11.3.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.19.3 in /usr/local/lib/python3.12/dist-packages (from transformers==4.40.2) (0.36.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers==4.40.2) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.40.2) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.40.2) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers==4.40.2) (2.32.4)
Requirement already satisfied: tokenizers<0.20,>=0.19 in /usr/local/lib/python3.12/dist-packages (from transformers==4.40.2) (0.19.1)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.40.2) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers==4.40.2) (4.67.1)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate==0.29.3) (5.9.5)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /usr/local/lib/python3.12/dist-packages (from nvidia-cusolver-cu12==11.4.5.107->torch==2.3.1) (12.6.85)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.19.3->transformers==4.40.2) (1.2.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch==2.3.1) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.40.2) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.40.2) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.40.2) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.40.2) (2026.1.4)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy->torch==2.3.1) (1.3.0)
Using cached torch-2.3.1-cp312-cp312-manylinux1_x86_64.whl (779.1 MB)
Using cached torchvision-0.18.1-cp312-cp312-manylinux1_x86_64.whl (7.0 MB)
Downloading transformers-4.40.2-py3-none-any.whl (9.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.0/9.0 MB 20.1 MB/s eta 0:00:00
Using cached accelerate-0.29.3-py3-none-any.whl (297 kB)
Installing collected packages: torch, transformers, torchvision, accelerate
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
sentence-transformers 5.2.0 requires transformers<6.0.0,>=4.41.0, but you have transformers 4.40.2 which is incompatible.
Successfully installed accelerate-0.29.3 torch-2.3.1 torchvision-0.18.1 transformers-4.40.2

In [ ]:
!pip uninstall -y sentence-transformers

Found existing installation: sentence-transformers 5.2.0
Uninstalling sentence-transformers-5.2.0:
  Successfully uninstalled sentence-transformers-5.2.0

In [ ]:
!pip uninstall -y peft

Found existing installation: peft 0.18.1
Uninstalling peft-0.18.1:
  Successfully uninstalled peft-0.18.1

In [ ]:
import importlib.util

print("peft installed?", importlib.util.find_spec("peft") is not None)

peft installed? False

In [ ]:
!pip install peft==0.9.0

Collecting peft==0.9.0
  Downloading peft-0.9.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from peft==0.9.0) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from peft==0.9.0) (25.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from peft==0.9.0) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from peft==0.9.0) (6.0.3)
Requirement already satisfied: torch>=1.13.0 in /usr/local/lib/python3.12/dist-packages (from peft==0.9.0) (2.3.1)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (from peft==0.9.0) (4.40.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from peft==0.9.0) (4.67.1)
Requirement already satisfied: accelerate>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from peft==0.9.0) (0.29.3)
Requirement already satisfied: safetensors in /usr/local/lib/python3.12/dist-packages (from peft==0.9.0) (0.7.0)
Requirement already satisfied: huggingface-hub>=0.17.0 in /usr/local/lib/python3.12/dist-packages (from peft==0.9.0) (0.36.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.17.0->peft==0.9.0) (3.20.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.17.0->peft==0.9.0) (2025.3.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.17.0->peft==0.9.0) (2.32.4)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.17.0->peft==0.9.0) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.17.0->peft==0.9.0) (1.2.0)
Requirement already satisfied: sympy in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.9.0) (1.14.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.9.0) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.9.0) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.9.0) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.9.0) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.9.0) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==8.9.2.26 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.9.0) (8.9.2.26)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.9.0) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.9.0) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.9.0) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.9.0) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.9.0) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.20.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.9.0) (2.20.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.9.0) (12.1.105)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /usr/local/lib/python3.12/dist-packages (from nvidia-cusolver-cu12==11.4.5.107->torch>=1.13.0->peft==0.9.0) (12.6.85)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers->peft==0.9.0) (2025.11.3)
Requirement already satisfied: tokenizers<0.20,>=0.19 in /usr/local/lib/python3.12/dist-packages (from transformers->peft==0.9.0) (0.19.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.13.0->peft==0.9.0) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.17.0->peft==0.9.0) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.17.0->peft==0.9.0) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.17.0->peft==0.9.0) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.17.0->peft==0.9.0) (2026.1.4)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy->torch>=1.13.0->peft==0.9.0) (1.3.0)
Downloading peft-0.9.0-py3-none-any.whl (190 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 190.9/190.9 kB 2.0 MB/s eta 0:00:00
Installing collected packages: peft
Successfully installed peft-0.9.0

In [ ]:
import torch
from transformers import Trainer, TrainingArguments

print("Torch:", torch.__version__)
print("Trainer import OK ✅")

Torch: 2.3.1+cu121
Trainer import OK ✅

In [ ]:
from google.colab import files
files.upload()

In [ ]:
!unzip liar_dataset.zip
!unzip Fake.csv.zip
!unzip True.csv.zip
!ls

Archive:  liar_dataset.zip
  inflating: README
  inflating: test.tsv
  inflating: train.tsv
  inflating: valid.tsv
Archive:  Fake.csv.zip
  inflating: Fake.csv
Archive:  True.csv.zip
  inflating: True.csv
Fake.csv      liar_dataset.zip	sample_data  train.tsv	True.csv.zip
Fake.csv.zip  README		test.tsv     True.csv	valid.tsv

In [ ]:
import os

print("train.tsv exists:", os.path.exists("train.tsv"))
print("Fake.csv exists:", os.path.exists("Fake.csv"))
print("True.csv exists:", os.path.exists("True.csv"))

train.tsv exists: True
Fake.csv exists: True
True.csv exists: True

In [ ]:
import pandas as pd

liar = pd.read_csv("train.tsv", sep="\t", header=None)

# column 2 = statement, column 1 = label
liar = liar[[2, 1]]
liar.columns = ["text", "label"]

fake_labels = ["false", "pants-fire", "barely-true"]

liar["label"] = liar["label"].apply(
    lambda x: 0 if x in fake_labels else 1
)

liar.head()

                                                text  label
0  Says the Annies List political group supports ...      0
1  When did the decline of coal start? It started...      1
2  Hillary Clinton agrees with John McCain "by vo...      1
3  Health care reform legislation is likely to ma...      0
4  The economic turnaround started at the end of ...      1

In [ ]:
fake = pd.read_csv("Fake.csv")
real = pd.read_csv("True.csv")

fake["label"] = 0
real["label"] = 1

fake = fake[["text", "label"]]
real = real[["text", "label"]]

fake.head(), real.head()

(                                                text  label
 0  Donald Trump just couldn t wish all Americans ...      0
 1  House Intelligence Committee Chairman Devin Nu...      0
 2  On Friday, it was revealed that former Milwauk...      0
 3  On Christmas day, Donald Trump announced that ...      0
 4  Pope Francis used his annual Christmas Day mes...      0,
                                                 text  label
 0  WASHINGTON (Reuters) - The head of a conservat...      1
 1  WASHINGTON (Reuters) - Transgender people will...      1
 2  WASHINGTON (Reuters) - The special counsel inv...      1
 3  WASHINGTON (Reuters) - Trump campaign adviser ...      1
 4  SEATTLE/WASHINGTON (Reuters) - President Donal...      1)

In [ ]:
df = pd.concat([liar, fake, real], ignore_index=True)
df = df.dropna()
df = df.sample(frac=1, random_state=42).reset_index(drop=True)

df["label"].value_counts()

label
0    27969
1    27169
Name: count, dtype: int64

In [ ]:
import re

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"[^a-zA-Z ]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

df["text"] = df["text"].apply(clean_text)
df.sample(5)

                                                    text  label
32599  where s the outcry from the left about the mis...      0
13405  president barack obama supports immigration am...      1
13175  the following statements were posted to the ve...      1
7363   gothenburg sweden reuters there is more work t...      1
8462   st century wire says while everyone is busy hy...      0

In [ ]:
print("Total samples:", len(df))
print(df.head())

Total samples: 55138
                                                text  label
0  andrew breitbart got under the skin of the lef...      0
1  trump s third day across seas may end up being...      0
2  at an addiction policy forum in in new hampshi...      0
3  ankara reuters iranians quickly closed ranks a...      1
4  among the developed nations we are the least e...      1

In [ ]:
from sklearn.model_selection import train_test_split

train_texts, temp_texts, train_labels, temp_labels = train_test_split(
    df["text"],
    df["label"],
    test_size=0.2,
    random_state=42,
    stratify=df["label"]
)

val_texts, test_texts, val_labels, test_labels = train_test_split(
    temp_texts,
    temp_labels,
    test_size=0.5,
    random_state=42,
    stratify=temp_labels
)

print(len(train_texts), len(val_texts), len(test_texts))

44110 5514 5514

In [ ]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

train_enc = tokenizer(
    list(train_texts),
    truncation=True,
    padding=True,
    max_length=256
)

val_enc = tokenizer(
    list(val_texts),
    truncation=True,
    padding=True,
    max_length=256
)

test_enc = tokenizer(
    list(test_texts),
    truncation=True,
    padding=True,
    max_length=256
)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:942: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

In [ ]:
import torch

class NewsDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels.tolist()

    def __getitem__(self, idx):
        item = {k: torch.tensor(v[idx]) for k, v in self.encodings.items()}
        item["labels"] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)

train_ds = NewsDataset(train_enc, train_labels)
val_ds   = NewsDataset(val_enc, val_labels)
test_ds  = NewsDataset(test_enc, test_labels)

In [ ]:
from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained(
    "bert-base-uncased",
    num_labels=2
)

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [ ]:
from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./model",
    evaluation_strategy="epoch",
    save_strategy="epoch",
    num_train_epochs=3,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    learning_rate=2e-5,
    weight_decay=0.01,
    load_best_model_at_end=True,
    metric_for_best_model="f1",
    report_to="none"
)

In [ ]:
from transformers import Trainer
from sklearn.metrics import accuracy_score, f1_score

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = logits.argmax(axis=1)
    return {
        "accuracy": accuracy_score(labels, preds),
        "f1": f1_score(labels, preds)
    }

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_ds,
    eval_dataset=val_ds,
    compute_metrics=compute_metrics
)

trainer.train()

TrainOutput(global_step=8271, training_loss=0.11543731495743434, metrics={'train_runtime': 6078.816, 'train_samples_per_second': 21.769, 'train_steps_per_second': 1.361, 'total_flos': 1.74087429778944e+16, 'train_loss': 0.11543731495743434, 'epoch': 3.0})

In [ ]:
from sklearn.metrics import classification_report

preds = trainer.predict(test_ds)
y_pred = preds.predictions.argmax(axis=1)

print(classification_report(test_labels, y_pred))

              precision    recall  f1-score   support

           0       0.95      0.91      0.93      2797
           1       0.91      0.95      0.93      2717

    accuracy                           0.93      5514
   macro avg       0.93      0.93      0.93      5514
weighted avg       0.93      0.93      0.93      5514

In [ ]:
model.save_pretrained("fake-news-bert")
tokenizer.save_pretrained("fake-news-bert")

('fake-news-bert/tokenizer_config.json',
 'fake-news-bert/special_tokens_map.json',
 'fake-news-bert/vocab.txt',
 'fake-news-bert/added_tokens.json',
 'fake-news-bert/tokenizer.json')

In [ ]:
!zip -r fake-news-bert.zip fake-news-bert

  adding: fake-news-bert/ (stored 0%)
  adding: fake-news-bert/special_tokens_map.json (deflated 42%)
  adding: fake-news-bert/tokenizer_config.json (deflated 76%)
  adding: fake-news-bert/vocab.txt (deflated 53%)
  adding: fake-news-bert/config.json (deflated 49%)
  adding: fake-news-bert/tokenizer.json (deflated 71%)
  adding: fake-news-bert/model.safetensors (deflated 7%)

In [ ]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch

tokenizer = AutoTokenizer.from_pretrained("fake-news-bert")
model = AutoModelForSequenceClassification.from_pretrained("fake-news-bert")

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
model.eval()

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): BertOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (pooler): BertPooler(
      (dense): Linear(in_features=768, out_features=768, bias=True)
      (activation): Tanh()
    )
  )
  (dropout): Dropout(p=0.1, inplace=False)
  (classifier): Linear(in_features=768, out_features=2, bias=True)
)

In [ ]:
import torch

def predict_news(text):
    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        padding=True,
        max_length=256
    ).to(device)

    with torch.no_grad():
        outputs = model(**inputs)
        probs = torch.softmax(outputs.logits, dim=1)

    idx = probs.argmax(dim=1).item()
    label = "REAL" if idx == 1 else "FAKE"
    confidence = round(probs[0][idx].item(), 4)

    return label, confidence


def predict_news_final(text):
    # 1. Input validation
    if not isinstance(text, str) or len(text.strip()) < 10:
        return "UNCERTAIN", 0.0

    label, confidence = predict_news(text)

    # 2. High confidence → trust model
    if confidence >= 0.90:
        return label, confidence

    # 3. Medium confidence → ambiguous
    if confidence >= 0.60:
        return "UNCERTAIN", confidence

    # 4. Low confidence → unclear
    return "UNCERTAIN", confidence

In [ ]:
cases = [
    "Drinking bleach cures all diseases.",
    "NASA confirms water on Mars.",
    "President announces new economic policy today.",
    "Aliens are living among us according to secret documents.",
    """
    According to the World Health Organization, vaccines are safe
    and effective in preventing infectious diseases.
    """
]

for c in cases:
    print(c.strip()[:80])
    print("→", predict_news_final(c))
    print("-" * 50)

Drinking bleach cures all diseases.
→ ('UNCERTAIN', 0.6572)
--------------------------------------------------
NASA confirms water on Mars.
→ ('UNCERTAIN', 0.8904)
--------------------------------------------------
President announces new economic policy today.
→ ('FAKE', 0.9996)
--------------------------------------------------
Aliens are living among us according to secret documents.
→ ('FAKE', 0.9942)
--------------------------------------------------
According to the World Health Organization, vaccines are safe
    and effective
→ ('REAL', 0.9577)
--------------------------------------------------

In [ ]:
test_cases = [
    "Drinking bleach cures all diseases.",
    "NASA confirms water on Mars.",
    "President announces new economic policy today.",
    "Aliens are living among us according to secret documents.",
    """
    According to the World Health Organization, vaccines are safe
    and effective in preventing infectious diseases.
    """
]

for i, text in enumerate(test_cases, 1):
    label, confidence = predict_news_safe(text)
    print(f"Case {i}:")
    print(text.strip()[:100], "...")
    print("→", label, confidence)
    print("-" * 50)

Case 1:
Drinking bleach cures all diseases. ...
→ UNCERTAIN 0.6572
--------------------------------------------------
Case 2:
NASA confirms water on Mars. ...
→ FAKE 0.8904
--------------------------------------------------
Case 3:
President announces new economic policy today. ...
→ FAKE 0.9996
--------------------------------------------------
Case 4:
Aliens are living among us according to secret documents. ...
→ FAKE 0.9942
--------------------------------------------------
Case 5:
According to the World Health Organization, vaccines are safe
    and effective in preventing infect ...
→ REAL 0.9577
--------------------------------------------------

In [ ]:
print(predict_news_safe("Breaking news"))

('FAKE', 0.9995)

In [ ]:
print(predict_news_safe(""))
print(predict_news_safe("!!! ??? ###"))

('FAKE', 0.9999)
('FAKE', 0.9999)

In [ ]:
long_text = """
The government today announced a comprehensive policy reform aimed at
improving economic stability, reducing inflation, and encouraging
foreign investment. Officials stated that the policy will be reviewed
annually and adjusted based on economic indicators.
"""

print(predict_news_safe(long_text))

('REAL', 0.9372)

In [ ]:
cases = {
    "Fake medical claim": "Drinking bleach cures all diseases.",
    "Short ambiguous headline": "NASA confirms water on Mars.",
    "Real scientific report": """
        NASA scientists confirmed the presence of water molecules
        on the surface of Mars using data from the Mars Reconnaissance Orbiter.
    """
}

for name, text in cases.items():
    label, confidence = predict_news_safe(text)
    print(f"{name}: {label} ({confidence})")

Fake medical claim: UNCERTAIN (0.6572)
Short ambiguous headline: FAKE (0.8904)
Real scientific report: REAL (0.9872)

In [ ]:
from google.colab import files
files.download("fake-news-bert.zip")